### ISSUE TITLE
Activity crashes on launch due to finishSetup()

### ISSUE THREAD

**Issue by vik17ag** [armcha/Vertical-Intro#2]
Hi,
I created an activity just like in your sample
Started it via explicit intent
But it crashed , below are logs-

It crashes at findAndSetupViews()...

I gind your library unique than others and I want to implement soon. Please help. 

11-09 15:17:05.180 4166-4166/vivekagarwal.playwithdb E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{vivekagarwal.playwithdb/vivekagarwal.playwithdb.screens.IntroDialogActivity}: java.lang.NullPointerException
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2180)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
                                                                           at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                           at android.os.Looper.loop(Looper.java:137)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5041)
                                                                           at java.lang.reflect.Method.invokeNative(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:511)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560)
                                                                           at dalvik.system.NativeStart.main(Native Method)
                                                                        Caused by: java.lang.NullPointerException
                                                                           at com.luseen.verticalintrolibrary.VerticalIntro.findAndSetupViews(VerticalIntro.java:282)
                                                                           at com.luseen.verticalintrolibrary.VerticalIntro.onCreate(VerticalIntro.java:62)
                                                                           at android.app.Activity.performCreate(Activity.java:5104)
                                                                           at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230) 
                                                                           at android.app.ActivityThread.access$600(ActivityThread.java:141) 
                                                                           at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234) 
                                                                           at android.os.Handler.dispatchMessage(Handler.java:99) 
                                                                           at android.os.Looper.loop(Looper.java:137) 
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5041) 
                                                                           at java.lang.reflect.Method.invokeNative(Native Method) 
                                                                           at java.lang.reflect.Method.invoke(Method.java:511) 
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:793) 
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:560) 
                                                                           at dalvik.system.NativeStart.main(Native Method)

**Comment by armcha** [comment]
@vik17ag please send me your part of code, where you set up vertical intro

**Comment by armcha** [comment]
For me it works just fine
```java
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        findViewById(R.id.button).setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                Intent intent = new Intent(MainActivity.this, TestActivity.class);
                startActivity(intent);
            }
        });
    }
}
```

**Comment by armcha** [comment]
Fixed
